#!/bin/sh

args=$@

eargs=""

abspath_root="$(git rev-parse --show-toplevel)/"


for i in $args; do
  eargs="$eargs -e $i "
done


stagedfiles=$(git ls-files)


searchpath_groups=""

cnt=0

flag=0

for i in $stagedfiles; do
  if test $cnt -gt 10 ; then
    grep $eargs $searchpath_groups && flag=1; 
    cnt=0
  fi
  searchpath_groups="$searchpath_groups $i"
  cnt=$((cnt+1))
done

if test $cnt -ne 0 ; then
  grep $eargs $searchpath_groups && flag=1;
fi

if test $flag -eq 1 ; then
  exit 1
else
  exit 0
fi



